### ISSUE TITLE
crypto and meta packages versions incompatible with flutter stable

### ISSUE THREAD

**Issue by savy-91** [statsig-io/dart-sdk#1]
Hi!

I was test running this sdk for a Flutter application and noticed that because of the `meta` and `crypto` dependencies constraints, this sdk is not compatible with the current Flutter stable version (3.0.5). More specifically, with the versions of `crypto` and `meta` used by `flutter_test` and `integration_test`.

If you do not need features available only in this specific versions of the packages, it would be great if you could use:

```

  meta: ^1.7.0
  crypto: ^3.0.1
  
```

I am using them as `dependency_override` but it would be better to have the sdk directly compatible with up to date Flutter versions.

**Comment by dan-loomb** [comment]
Yup, this is fine. Thanks for the diff.

**Comment by guillempuche** [comment]
@savy-91 , `meta` should work on the latest release `0.3.1`

I'm testing it with Flutter 2.10.5

**Comment by savy-91** [comment]
> 

Are you also using `flutter_test` and/or` integration_test`?

**Comment by guillempuche** [comment]
We're using `flutter_test`

**Comment by savy-91** [comment]
@guillempuche Yes it does work now, my PR was merged in fact : https://github.com/statsig-io/dart-sdk/pull/5
